// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonRelay = require("reason-relay/src/ReasonRelay.bs.js");
var TodoList$MywWebapp = require("./TodoList.bs.js");
var TodoTextInput$MywWebapp = require("./TodoTextInput.bs.js");
var TodoListFooter$MywWebapp = require("./TodoListFooter.bs.js");
var AddTodoMutation$MywWebapp = require("../mutations/AddTodoMutation.bs.js");
var TodoApp_user_graphql$MywWebapp = require("../__generated__/TodoApp_user_graphql.bs.js");

var UseFragment = ReasonRelay.MakeUseFragment(/* module */[/* fragmentSpec */TodoApp_user_graphql$MywWebapp.node]);

function use(fRef) {
  return Curry._1(UseFragment[/* use */0], fRef);
}

var UserFragment = /* module */[
  /* Operation */0,
  /* UseFragment */UseFragment,
  /* use */use
];

function TodoApp(Props) {
  var userRef = Props.user;
  var user = Curry._1(UseFragment[/* use */0], userRef);
  var environment = ReasonRelay.useEnvironmentFromContext(/* () */0);
  var handleTextInputSave = function (text) {
    return AddTodoMutation$MywWebapp.commit(environment, text, user);
  };
  var hasTodos = user.totalCount > 0;
  return React.createElement("div", undefined, React.createElement("section", {
                  className: "todoapp"
                }, React.createElement("header", {
                      className: "header"
                    }, React.createElement("h1", undefined, "todos")), React.createElement(TodoTextInput$MywWebapp.make, {
                      className: "new-todo",
                      onSave: handleTextInputSave,
                      placeholder: "What needs to be done?"
                    }), React.createElement(TodoList$MywWebapp.make, {
                      user: user
                    }), hasTodos ? React.createElement(TodoListFooter$MywWebapp.make, {
                        user: user
                      }) : null), React.createElement("footer", {
                  className: "info"
                }, React.createElement("p", undefined, "Double-click to edit a todo"), React.createElement("p", undefined, "Created by the Relay community"), React.createElement("p", undefined, "Part of ", React.createElement("a", {
                          href: "http://todomvc.com"
                        }, "TodoMVC"))));
}

var make = TodoApp;

exports.UserFragment = UserFragment;
exports.make = make;
/* UseFragment Not a pure module */
