// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonRelay = require("reason-relay/src/ReasonRelay.bs.js");
var ReasonRelayUtils = require("reason-relay/src/ReasonRelayUtils.bs.js");
var TodoListFooter_user_graphql$MywWebapp = require("../__generated__/TodoListFooter_user_graphql.bs.js");
var RemoveCompletedTodosMutation$MywWebapp = require("../mutations/RemoveCompletedTodosMutation.bs.js");

var UseFragment = ReasonRelay.MakeUseFragment(/* module */[/* fragmentSpec */TodoListFooter_user_graphql$MywWebapp.node]);

function use(fRef) {
  return Curry._1(UseFragment[/* use */0], fRef);
}

var UserFragment = /* module */[
  /* Operation */0,
  /* UseFragment */UseFragment,
  /* use */use
];

function TodoListFooter(Props) {
  var userRef = Props.user;
  var user = Curry._1(UseFragment[/* use */0], userRef);
  var environment = ReasonRelay.useEnvironmentFromContext(/* () */0);
  var completedTodos = Belt_Array.keepMap(ReasonRelayUtils.collectConnectionNodesFromNullable(user.todos), (function (node) {
          var match = node.complete;
          if (match) {
            return Caml_option.some(node);
          }
          
        }));
  var handleRemoveCompletedTodosClick = function (param) {
    RemoveCompletedTodosMutation$MywWebapp.commit(environment, completedTodos, user);
    return /* () */0;
  };
  var numRemainingTodos = user.totalCount - user.completedCount | 0;
  var match = numRemainingTodos === 1;
  var match$1 = user.completedCount > 0;
  return React.createElement("footer", {
              className: "footer"
            }, React.createElement("span", {
                  className: "todo-count"
                }, React.createElement("strong", undefined, String(numRemainingTodos)), " item", match ? null : "s", " left"), match$1 ? React.createElement("button", {
                    className: "clear-completed",
                    onClick: handleRemoveCompletedTodosClick
                  }, "Clear completed") : null);
}

var make = TodoListFooter;

exports.UserFragment = UserFragment;
exports.make = make;
/* UseFragment Not a pure module */
