// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var ReasonRelay = require("reason-relay/src/ReasonRelay.bs.js");
var TodoApp$MywWebapp = require("./components/TodoApp.bs.js");
var RelayEnv$MywWebapp = require("./RelayEnv.bs.js");
var AppQuery_graphql$MywWebapp = require("./__generated__/AppQuery_graphql.bs.js");

var UseQuery = ReasonRelay.MakeUseQuery(/* module */[/* query */AppQuery_graphql$MywWebapp.node]);

var use = UseQuery[/* use */0];

function $$fetch(environment, variables) {
  return ReasonRelay.fetchQuery(environment, AppQuery_graphql$MywWebapp.node, variables);
}

var Query = /* module */[
  /* Operation */0,
  /* UseQuery */UseQuery,
  /* use */use,
  /* fetch */$$fetch
];

function App$AppDisplayer(Props) {
  var query = Curry._3(use, {
        userId: "me"
      }, undefined, /* () */0);
  if (typeof query === "number") {
    return React.createElement("div", undefined, "Loading");
  } else if (query.tag) {
    var match = query[0].user;
    if (match == null) {
      return "Something went wrong!";
    } else {
      return React.createElement(TodoApp$MywWebapp.make, {
                  user: match
                });
    }
  } else {
    return React.createElement("div", undefined, Belt_Option.getWithDefault(query[0].message, "Something went wrong!"));
  }
}

var AppDisplayer = /* module */[/* make */App$AppDisplayer];

ReactDOMRe.renderToElementWithId(React.createElement(ReasonRelay.Context[/* Provider */1][/* make */1], Curry._4(ReasonRelay.Context[/* Provider */1][/* makeProps */0], RelayEnv$MywWebapp.environment, React.createElement(App$AppDisplayer, { }), undefined, /* () */0)), "root");

exports.Query = Query;
exports.AppDisplayer = AppDisplayer;
/* UseQuery Not a pure module */
