// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE
'use strict';

var Fetch = require("bs-fetch/src/Fetch.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonRelay = require("reason-relay/src/ReasonRelay.bs.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var Graphql_error = Caml_exceptions.create("RelayEnv-MywWebapp.Graphql_error");

function fetchQuery(operation, variables, _cacheConfig) {
  return fetch("/graphql", Fetch.RequestInit[/* make */0](/* Post */2, {
                      "content-type": "application/json",
                      accept: "application/json"
                    }, Caml_option.some(JSON.stringify(Js_dict.fromList(/* :: */[
                                  /* tuple */[
                                    "query",
                                    operation.text
                                  ],
                                  /* :: */[
                                    /* tuple */[
                                      "variables",
                                      variables
                                    ],
                                    /* [] */0
                                  ]
                                ]))), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* () */0)).then((function (resp) {
                if (resp.ok) {
                  return resp.json();
                } else {
                  return Promise.reject([
                              Graphql_error,
                              "Request failed: " + resp.statusText
                            ]);
                }
              }));
}

var network = ReasonRelay.Network[/* makePromiseBased */0](fetchQuery);

function makeEnvironment(param) {
  return ReasonRelay.Environment[/* make */0](network, ReasonRelay.Store[/* make */0](ReasonRelay.RecordSource[/* make */0](/* () */0)), undefined, /* () */0);
}

var environment = makeEnvironment(/* () */0);

exports.Graphql_error = Graphql_error;
exports.fetchQuery = fetchQuery;
exports.network = network;
exports.makeEnvironment = makeEnvironment;
exports.environment = environment;
/* network Not a pure module */
