// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$String = require("bs-platform/lib/js/string.js");

function makeClassNames(classNames) {
  return $$String.concat(" ", List.map((function (param) {
                    if (param[1]) {
                      return param[0] + " ";
                    } else {
                      return "";
                    }
                  }), classNames));
}

exports.makeClassNames = makeClassNames;
/* No side effect */
